version: '3'

services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "8501:8501"
    # command: streamlit run app.py
    command: streamlit run my_app.py --server.port 8501 --server.baseUrlPath / --server.enableCORS false --server.enableXsrfProtection false

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app