version: '3'

services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "8501:8501"
    command: streamlit run app.py

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "3001:3001"
    depends_on:
      - app
    # toffy volume
    volumes:
      - ./landing_page:/usr/share/nginx/html

  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
      - "5432:5432"
    environment:
      # PGRST_DB_URI: postgres://app_user:password@db:5432/app_db  original
      # PGRST_DB_URI: postgres://authenticator:pass@localhost:5432/postgres #2nd 
      PGRST_DB_URI: postgres://authenticator:pass@10.0.0.10/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000 #original
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: web_anon
      
    # depends_on: original
    #   - db

  # docker run --rm --net=host \
  # -e PGRST_DB_URI="postgres://app_user:password@localhost/postgres" \
  # postgrest/postgrest

  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: app_db
  #     POSTGRES_USER: app_user
  #     POSTGRES_PASSWORD: password
  # Uncomment this if you want to persist the data.
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data"