version: "3"

services:

  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "8501:8501"
    command: streamlit run app.py

  client:
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d/
    # command: rm /etc/nginx/conf.d/default.conf

  # healthcheck:
  #   test: curl --fail http://localhost || exit 1
  #   # interval: 60s
  #   retries: 5
  #   start_period: 20s
  #   timeout: 10s